const products = [
    {
        "id": "apollo-deck-plus",
        "name": "Apollo Deck Plus",
        "brand": "Annova",
        "image": "img/Apollo_Deckplus.jpg",
        "weight": 3.6,
        "measure_unit": "l",
        "type": "coverage",
        "value": 10,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "10 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "pdf/ANNOVA-FISPQ - AN_2055 Deck Plus Acetinado.pdf",
        "bulletin": "pdf/ANNOVA-BT - AN _2055 DeckPlus Original.pdf",
        "composition": "LÍQUIDO DE POLÍMEROS PU/ ACRILATOS EMULSIONADOS EM ÁGUA E ADITIVOS COMPONENTES PERIGOSOS COMPONENTEAPROX",
        "odor": "CARACTERÍSTICO",
        "color": "AMARELADO",
        "consistency": "LIQUIDO",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "2 Horas (Ao toque) / 48-72 Horas (Total)",
        "cure_time": "30 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "apollo-ec-2k",
        "name": "Apollo EC-2K",
        "brand": "Annova",
        "image": "img/Apollo_Economico2K.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 14,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "14 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "pdf/ANNOVA-FISPQ - AN_2017 2K Apollo EC 2K Acetinado.pdf",
        "bulletin": "pdf/ANNOVA-BT - AN _2017 Apollo Economico 2K Acetinado.pdf",
        "composition": "LÍQUIDO DE COPOLÍMEROS PU/ ACRILATOS EMULSIONADOS EM ÁGUA E ADITIVOS COMPONENTES PERIGOSOS COMPONENTEAPROX",
        "odor": "CARACTERÍSTICO",
        "color": "BRANCO LEITOSOp H DILUIDO (1% p/p): N/A",
        "consistency": "LÍQUIDOp H PURO: 7,5 A 8,5",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "2 Horas (Ao toque) / 48-72 Horas (Total)",
        "cure_time": "30 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "apollo-economico",
        "name": "Apollo Econômico",
        "brand": "Annova",
        "image": "img/Apollo_Economico.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 14,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "14 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "pdf/ANNOVA-FISPQ - AN_2015 Resistente Acetinado.pdf",
        "bulletin": "pdf/ANNOVA-BT - AN _2017 Apollo Economico Acetinado.pdf",
        "composition": "LÍQUIDO DE COPOLÍMEROS PU/ ACRILATOS EMULSIONADOS EM ÁGUA E ADITIVOS COMPONENTES PERIGOSOS COMPONENTEAPROX",
        "odor": "CARACTERÍSTICO",
        "color": "BRANCO LEITOSOp H DILUIDO (1% p/p): N/A",
        "consistency": "LÍQUIDOp H PURO: 7,5 A 8,5",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "2 Horas (Ao toque) / 48-72 Horas (Total)",
        "cure_time": "30 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "apollo-hd-at",
        "name": "Apollo HD AT",
        "brand": "Annova",
        "image": "img/Apollo_AT-HD.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 14,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "14 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "pdf/ANNOVA-FISPQ - AN_2045 AT HD Acetinado.pdf",
        "bulletin": "pdf/ANNOVA-BT - AN _2045 Apollo AT HD Acetinado.pdf",
        "composition": "LÍQUIDO DE COPOLÍMEROS PU/ ACRILATOS EMULSIONADOS EM ÁGUA E ADITIVOS COMPONENTES PERIGOSOS COMPONENTEAPROX",
        "odor": "CARACTERÍSTICO",
        "color": "BRANCO LEITOSOp H DILUIDO (1% p/p): N/A",
        "consistency": "LÍQUIDOp H PURO: 7,5 A 8,5",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "2 Horas (Ao toque) / 48-72 Horas (Total)",
        "cure_time": "30 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "apollo-innovare",
        "name": "Apollo Innovare",
        "brand": "Annova",
        "image": "img/Apollo_Innovare.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 14,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "14 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "pdf/ANNOVA-FISPQ - AN_2075 Innovare Acetinado.pdf",
        "bulletin": "pdf/ANNOVA-BT - AN _2075 Apollo Innovare Acetinado.pdf",
        "composition": "LÍQUIDO DE COPOLÍMEROS PU/ ACRILATOS EMULSIONADOS EM ÁGUA E ADITIVOS COMPONENTES PERIGOSOS COMPONENTEAPROX",
        "odor": "CARACTERÍSTICO",
        "color": "BRANCO LEITOSOp H DILUIDO (1% p/p): N/A",
        "consistency": "LÍQUIDOp H PURO: 7,5 A 8,5",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "2 Horas (Ao toque) / 48-72 Horas (Total)",
        "cure_time": "30 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "apollo-limpador",
        "name": "Apollo Limpador Concentrado",
        "brand": "Annova",
        "image": "img/Apollo_Limpador.jpg",
        "weight": 1,
        "measure_unit": "l",
        "type": "coverage",
        "value": 70,
        "unit": "M²/L (Concentrado)",
        "ncm": "3402.39.90",
        "cest": "11.007.00",
        "barcode": "n/a",
        "model": "1L",
        "category": "Acabamento",
        "coverage": "70 M²/L (Concentrado)",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "pdf/ANNOVA-FISPQ - AN_2100 Limpador.pdf",
        "bulletin": "pdf/ANNOVA-BT - AN _2100 Apollo Limpador Concentrado.pdf",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "n/a",
        "drying_time": "n/a",
        "cure_time": "n/a",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "apollo-original",
        "name": "Apollo Original",
        "brand": "Annova",
        "image": "img/Apollo_Original.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 14,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "14 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "pdf/ANNOVA-FISPQ - AN_2051 Apollo Original.pdf",
        "bulletin": "pdf/ANNOVA-BT - AN _2051 Apollo Original.pdf",
        "composition": "LÍQUIDO DE COPOLÍMEROS PU/ ACRILATOS EMULSIONADOS EM ÁGUA E ADITIVOS COMPONENTES PERIGOSOS COMPONENTEAPROX",
        "odor": "CARACTERÍSTICO",
        "color": "BRANCO LEITOSOp H DILUIDO (1% p/p): N/A",
        "consistency": "LÍQUIDOp H PURO: 7,5 A 8,5",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "2 Horas (Ao toque) / 48-72 Horas (Total)",
        "cure_time": "30 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "apollo-resistente",
        "name": "Apollo Resistente",
        "brand": "Annova",
        "image": "img/Apollo_Resistente.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 16,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "16 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "pdf/ANNOVA-FISPQ - AN_2015 Resistente Acetinado.pdf",
        "bulletin": "pdf/ANNOVA-BT - AN _2015 Apollo Resistnte Acetinado.pdf",
        "composition": "LÍQUIDO DE COPOLÍMEROS PU/ ACRILATOS EMULSIONADOS EM ÁGUA E ADITIVOS COMPONENTES PERIGOSOS COMPONENTEAPROX",
        "odor": "CARACTERÍSTICO",
        "color": "BRANCO LEITOSOp H DILUIDO (1% p/p): N/A",
        "consistency": "LÍQUIDOp H PURO: 7,5 A 8,5",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "2 Horas (Ao toque) / 48-72 Horas (Total)",
        "cure_time": "30 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "apollo-selaclass",
        "name": "Apollo SelaClass",
        "brand": "Annova",
        "image": "img/Apollo_Selaclass.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 12,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "12 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "pdf/ANNOVA-FISPQ - AN_2015 Resistente Acetinado.pdf",
        "bulletin": "pdf/ANNOVA-BT - AN _2015 Apollo Resistnte Acetinado.pdf",
        "composition": "LÍQUIDO DE COPOLÍMEROS PU/ ACRILATOS EMULSIONADOS EM ÁGUA E ADITIVOS COMPONENTES PERIGOSOS COMPONENTEAPROX",
        "odor": "CARACTERÍSTICO",
        "color": "BRANCO LEITOSOp H DILUIDO (1% p/p): N/A",
        "consistency": "LÍQUIDOp H PURO: 7,5 A 8,5",
        "tonality": "n/a",
        "drying_time": "2 Horas (Ao toque) / 48-72 Horas (Total)",
        "cure_time": "30 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "apollo-seladora-A",
        "name": "Apollo Seladora A",
        "brand": "Annova",
        "image": "img/Apollo_SeladoraA.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 12,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "12 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "pdf/ANNOVA-FISPQ - AN_2015 Resistente Acetinado.pdf",
        "bulletin": "pdf/ANNOVA-BT - AN _2015 Apollo Resistnte Acetinado.pdf",
        "composition": "LÍQUIDO DE COPOLÍMEROS PU/ ACRILATOS EMULSIONADOS EM ÁGUA E ADITIVOS COMPONENTES PERIGOSOS COMPONENTEAPROX",
        "odor": "CARACTERÍSTICO",
        "color": "BRANCO LEITOSOp H DILUIDO (1% p/p): N/A",
        "consistency": "LÍQUIDOp H PURO: 7,5 A 8,5",
        "tonality": "n/a",
        "drying_time": "2 Horas (Ao toque) / 48-72 Horas (Total)",
        "cure_time": "30 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "apollo-seladora-RAF",
        "name": "Apollo Seladora R.A-F",
        "brand": "Annova",
        "image": "img/Apollo_SeladoraRAF.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 12,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "12 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "pdf/ANNOVA-FISPQ - AN_2130 Restaurador Acetinado-Fosco.pdf",
        "bulletin": "pdf/ANNOVA-BT - AN _2015 Apollo Resistnte Acetinado.pdf",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "n/a",
        "drying_time": "2 Horas (Ao toque) / 48-72 Horas (Total)",
        "cure_time": "30 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "bona-classic-ux",
        "name": "Bona Classic UX",
        "brand": "Bona",
        "image": "img/Bona_ClassicUX.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 10,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "10 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "2 a 3 Horas (Entre demãos) / 24 Horas (Tráfego leve)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "bona-decking-oil",
        "name": "Bona Decking Oil",
        "brand": "Bona",
        "image": "img/Bona_DeckOil.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 20,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "20 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "2 a 3 Horas (Entre demãos) / 24 Horas (Tráfego leve)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "bona-domo",
        "name": "Bona Domo",
        "brand": "Bona",
        "image": "img/Bona_Domo.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 10,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "10 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "2 a 3 Horas (Entre demãos) / 24 Horas (Tráfego leve)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "bona-mega",
        "name": "Bona Mega",
        "brand": "Bona",
        "image": "img/Bona_Mega.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 10,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "10 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "2 a 3 Horas (Entre demãos) / 24 Horas (Tráfego leve)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "bona-refresher",
        "name": "Bona Refresher",
        "brand": "Bona",
        "image": "img/Bona_Freshenup.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 50,
        "unit": "M²/L",
        "ncm": "3402.39.90",
        "cest": "11.007.00",
        "barcode": "n/a",
        "model": "1L",
        "category": "Acabamento",
        "coverage": "50 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "n/a",
        "drying_time": "n/a",
        "cure_time": "n/a",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "bona-traffic-go",
        "name": "Bona Traffic GO",
        "brand": "Bona",
        "image": "img/Bona_TrafficGO.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 10,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "10 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "2 a 3 Horas (Entre demãos) / 24 Horas (Tráfego leve)",
        "cure_time": "3 a 7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "bona-traffic-hd",
        "name": "Bona Traffic HD",
        "brand": "Bona",
        "image": "img/Bona_TrafficHD.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 10,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "10 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "2 a 3 Horas (Entre demãos) / 24 Horas (Tráfego leve)",
        "cure_time": "3 a 7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "bona-wave-2k",
        "name": "Bona Wave 2k",
        "brand": "Bona",
        "image": "img/Bona_Wave2K.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 10,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "10 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "2 a 3 Horas (Entre demãos) / 24 Horas (Tráfego leve)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "bonardi-vernice",
        "name": "Bonardi Vernice (5L/10L/20L)",
        "brand": "Bonardi",
        "image": "img/Bonardi_Acet.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 10,
        "unit": "M²/L",
        "ncm": "3909.10.00",
        "cest": "28.057.00",
        "barcode": "n/a",
        "model": "5L/10L/20L",
        "category": "Acabamento",
        "coverage": "10 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "12 Horas (Entre demãos) / 48-72h (Tráfego)",
        "cure_time": "30 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "hdflex-cola-pu",
        "name": "Cola PU HD Flex (Pisos de Madeira)",
        "brand": "HDFlex",
        "image": "img/HDFlex_HDFloor.jpg",
        "weight": 5,
        "measure_unit": "kg",
        "type": "consumption",
        "value": 4,
        "unit": "M²/Kg",
        "ncm": "3506.91.90",
        "cest": "28.063.00",
        "barcode": "n/a",
        "model": "5kg",
        "category": "Acabamento",
        "coverage": "4 M²/Kg",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "n/a",
        "drying_time": "30 a 40 Minutos (Pot Life)",
        "cure_time": "24 Horas",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão",
        "usage": "Fixação de pisos de madeira"
    },
    {
        "id": "hdflex-cola-pu-colagem",
        "name": "Cola PU - HD Flex (Colagem)",
        "brand": "HDFlex",
        "image": "img/HDFlex_HDFloor.jpg",
        "weight": 5,
        "measure_unit": "kg",
        "type": "consumption",
        "value": 0.3,
        "unit": "M²/Kg",
        "ncm": "3506.91.90",
        "cest": "28.063.00",
        "barcode": "n/a",
        "model": "Standard",
        "category": "Acabamento",
        "coverage": "0.3 M²/Kg",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "n/a",
        "drying_time": "30 a 40 Minutos (Pot Life)",
        "cure_time": "24 Horas",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "hdflex-cola-pu-pva",
        "name": "Cola PU PVA Taco",
        "brand": "HDFlex",
        "image": "img/HDFlex_PVA.jpg",
        "weight": 5,
        "measure_unit": "kg",
        "type": "consumption",
        "value": 1,
        "unit": "M²/Kg",
        "ncm": "3506.91.90",
        "cest": "28.063.00",
        "barcode": "n/a",
        "model": "Standard",
        "category": "Acabamento",
        "coverage": "1 M²/Kg",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "E INFORMAÇÕES SOBRE OS INGREDIENTES - Natureza do Produto:Mistura - Nome químico ou comum / Natureza química: Preparação aquosa de poli (acetato de vinilo) Ingredientes ou impurezas que contribuam para o perigo - Nome químico ou comum: 1,2-Benzo-Isotiazol-3(2H)-ona Nº CAS:2634-33-5 Número EINECS:220-120-9 Concentração ou faixa de concentração:>=0,114 - <= 0,126% Sistema de classificação utilizado: Classificação NBR 14725-2 (GHS) Classe de perigoCategoriaFrases de perigo Toxicidade agudaCategoria 2H330 Toxicidade agudaCategoria 4H302 Irritação na peleCategoria 2H315 Lesão grave nos olhosCategoria 1H318 Sensibilização da peleCategoria 1BH317 Toxicidade aguda em meio aquático Categoria 1H400 Toxicidade crônica em meio aquático Categoria 2H411 Os textos das frases de perigo estão descritos na seção 16",
        "odor": "Característico pH:5,5– 7,5 (25°C)– Foi definido não diluído",
        "color": "Branco",
        "consistency": "(estado físico, forma, cor) Estado físico:líquido Forma:líquida",
        "tonality": "n/a",
        "drying_time": "30 a 40 Minutos (Pot Life)",
        "cure_time": "24 Horas",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "hdflex-cola-pu-uniq",
        "name": "Cola PU Uniq - HD Flex (Calafetacao)",
        "brand": "HDFlex",
        "image": "img/HDFlex_UNIQ.jpg",
        "weight": 5,
        "measure_unit": "kg",
        "type": "consumption",
        "value": 4,
        "unit": "M²/Kg",
        "ncm": "3506.91.90",
        "cest": "28.063.00",
        "barcode": "n/a",
        "model": "Standard",
        "category": "Acabamento",
        "coverage": "4 M²/Kg",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "n/a",
        "drying_time": "30 a 40 Minutos (Pot Life)",
        "cure_time": "24 Horas",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "hdflex-cola-pu-uniq-colagem",
        "name": "Cola PU Uniq - HD Flex (Colagem)",
        "brand": "HDFlex",
        "image": "img/HDFlex_UNIQ.jpg",
        "weight": 5,
        "measure_unit": "kg",
        "type": "consumption",
        "value": 0.3,
        "unit": "M²/Kg",
        "ncm": "3506.91.90",
        "cest": "28.063.00",
        "barcode": "n/a",
        "model": "Standard",
        "category": "Acabamento",
        "coverage": "0.3 M²/Kg",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "n/a",
        "drying_time": "30 a 40 Minutos (Pot Life)",
        "cure_time": "24 Horas",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "hdflex-cola-rodape",
        "name": "Cola Rodapé HD Flex (Metro Linear)",
        "brand": "HDFlex",
        "image": "img/HDFlex_ColaRodape.jpg",
        "weight": 5,
        "measure_unit": "kg",
        "type": "consumption",
        "value": 0.1,
        "unit": "Gramas/Metro Linear",
        "ncm": "3506.91.90",
        "cest": "28.063.00",
        "barcode": "n/a",
        "model": "Standard",
        "category": "Acabamento",
        "coverage": "0.1 Gramas/Metro Linear",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "n/a",
        "drying_time": "30 a 40 Minutos (Pot Life)",
        "cure_time": "24 Horas",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "hdflex-cola-vinilico",
        "name": "Cola p/ Piso Vinílico HD Flex",
        "brand": "HDFlex",
        "image": "img/HDFlex_ColaVinilica.jpg",
        "weight": 5,
        "measure_unit": "kg",
        "type": "consumption",
        "value": 0.3,
        "unit": "M²/Kg",
        "ncm": "3506.91.90",
        "cest": "28.063.00",
        "barcode": "n/a",
        "model": "Standard",
        "category": "Acabamento",
        "coverage": "0.3 M²/Kg",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "n/a",
        "drying_time": "30 a 40 Minutos (Pot Life)",
        "cure_time": "24 Horas",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "hdflex-manta-3000",
        "name": "Manta HD Flex 3000 PLUS",
        "brand": "HDFlex",
        "image": "img/HDFlex_HD3000.jpg",
        "weight": 5,
        "measure_unit": "kg",
        "type": "consumption",
        "value": 1,
        "unit": "M²/Kg",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "Standard",
        "category": "Acabamento",
        "coverage": "1 M²/Kg",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "3 a 4 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "hdflex-massa-calafeto",
        "name": "Massa Calafeto Acrílica FlexCrill",
        "brand": "HDFlex",
        "image": "img/HDFlex_Flexcrill.jpg",
        "weight": 5,
        "measure_unit": "kg",
        "type": "consumption",
        "value": 0.1,
        "unit": "M²/Kg",
        "ncm": "3214.10.20",
        "cest": "28.999.00",
        "barcode": "n/a",
        "model": "Standard",
        "category": "Acabamento",
        "coverage": "0.1 M²/Kg",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "n/a",
        "drying_time": "30 a 60 Minutos",
        "cure_time": "24 Horas",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "hdflex-superfix",
        "name": "Superfix HD Flex - Endurecedor",
        "brand": "HDFlex",
        "image": "img/HDFlex_Superfix.jpg",
        "weight": 5,
        "measure_unit": "kg",
        "type": "consumption",
        "value": 2,
        "unit": "M²/Kg",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "Standard",
        "category": "Acabamento",
        "coverage": "2 M²/Kg",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "3 a 4 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "klingspor-discos",
        "name": "Discos de Corte/Desbaste Klingspor",
        "brand": "Klingspor",
        "image": "https://placehold.co/500x500",
        "weight": 1,
        "measure_unit": "unid",
        "type": "manual",
        "value": 20,
        "unit": "unid",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "Standard",
        "category": "Acabamento",
        "coverage": "20 unid",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "3 a 4 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão",
        "note": "Rendimento varia conforme uso (abrasivo)"
    },
    {
        "id": "loba-2k-invisible",
        "name": "Loba 2k Invisible Protect",
        "brand": "Loba",
        "image": "img/Loba_2KInvisibleprotect.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 10,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "10 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Fosco",
        "drying_time": "4 a 6 Horas (Entre demãos) / 24 Horas (Tráfego leve)",
        "cure_time": "5 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "loba-2k-supra",
        "name": "Loba 2k Supra",
        "brand": "Loba",
        "image": "img/Loba_2KSupraAT.jpeg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 10,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "10 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "4 a 6 Horas (Entre demãos) / 24 Horas (Tráfego leve)",
        "cure_time": "5 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "loba-ws-2k-duo",
        "name": "Loba WS 2k Duo",
        "brand": "Loba",
        "image": "img/Loba_WS2KDuo.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 10,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "10 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "4 a 6 Horas (Entre demãos) / 24 Horas (Tráfego leve)",
        "cure_time": "5 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "loba-ws-easyfinish",
        "name": "Loba WS EasyFinish",
        "brand": "Loba",
        "image": "img/Loba_Easyfinish.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 10,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "10 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "4 a 6 Horas (Entre demãos) / 24 Horas (Tráfego leve)",
        "cure_time": "5 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "loba-ws-easyprime",
        "name": "Loba WS EasyPrime",
        "brand": "Loba",
        "image": "img/Loba_Easyprime.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 12,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "12 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "4 a 6 Horas (Entre demãos) / 24 Horas (Tráfego leve)",
        "cure_time": "5 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "primma-2k-plus",
        "name": "Primma 2k Plus",
        "brand": "Primma",
        "image": "img/Primma_2Kplus.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 14,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "Use luvas, mantenha fora do alcance de crianças e animais domésticos, evite contato prolongado com a pele ou inalação de vapor",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "pdf/PRIMMA-FISPQ-2K-PLUS-BRILHO.pdf",
        "bulletin": "pdf/PRIMMA-BT-2K-PLUS-SEMI-BRILHO.pdf",
        "composition": "LÍQUIDO DE POLÍMEROS PU/ ACRILATOS EMULSIONADOS EM ÁGUA E ADITIVOS COMPONENTES PERIGOSOS COMPONENTEAPROX",
        "odor": "CARACTERÍSTICO",
        "color": "AMARELADO",
        "consistency": "LIQUIDO",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "1 a 2 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "primma-base",
        "name": "Primma Base - Seladora",
        "brand": "Primma",
        "image": "img/Primma_Base.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 14,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "Use luvas, mantenha fora do alcance de crianças e animais domésticos, evite contato prolongado com a pele ou inalação de vapor",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "pdf/PRIMMA-BT-BASE.pdf",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "n/a",
        "drying_time": "1 a 2 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "primma-gold",
        "name": "Primma Gold",
        "brand": "Primma",
        "image": "img/Primma_Gold.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 14,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "Use luvas, mantenha fora do alcance de crianças e animais domésticos, evite contato prolongado com a pele ou inalação de vapor",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "pdf/PRIMMA-FISQP-GOLD-SEMI-BRILHO.pdf",
        "bulletin": "pdf/PRIMMA-BT-GOLD-SEMI-BRILHO.pdf",
        "composition": "GASES E VAPORES IRRITANTES",
        "odor": "CARACTERÍSTICO",
        "color": "INCOLORp H DILUIDO (1% p/p): N/A",
        "consistency": "LÍQUIDOp H PURO: 7,5 A 8,5",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "1 a 2 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "primma-ht-2k",
        "name": "Primma HT 2K",
        "brand": "Primma",
        "image": "img/Primma_HT-2K.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 14,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "Use luvas, mantenha fora do alcance de crianças e animais domésticos, evite contato prolongado com a pele ou inalação de vapor",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "pdf/PRIMMA-BT-HT-2K-SEMI-BRILHO.pdf",
        "composition": "GASES E VAPORES IRRITANTES",
        "odor": "CARACTERÍSTICO",
        "color": "INCOLORp H DILUIDO (1% p/p): N/A",
        "consistency": "LÍQUIDOp H PURO: 7,5 A 8,5",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "1 a 2 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "primma-piso-duro",
        "name": "Primma Piso Duro",
        "brand": "Primma",
        "image": "img/Primma_Pisoduro.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 14,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "Use luvas, mantenha fora do alcance de crianças e animais domésticos, evite contato prolongado com a pele ou inalação de vapor",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "pdf/PRIMMA-BT-PISO-DURO-SEMI-BRILHO.pdf",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "1 a 2 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "primma-primer",
        "name": "Primma Primer - Seladora",
        "brand": "Primma",
        "image": "img/Primma_Primer.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 14,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "A superfície a ser aplicado o “PRIMER” (base seladora) deverá estar previamente lixada com lixa 120 ou mais fina, totalmente isenta de pó e seca",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "pdf/PRIMMA-BT-PRIMER.pdf",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "n/a",
        "drying_time": "1 a 2 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "primma-sela-flash",
        "name": "Primma Sela Flash - Seladora",
        "brand": "Primma",
        "image": "img/Primma_Selaflash.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 14,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "Use luvas, mantenha fora do alcance de crianças e animais domésticos, evite contato prolongado com a pele ou inalação de vapor",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "pdf/PRIMMA-BT-SELAFLASH.pdf",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "n/a",
        "drying_time": "1 a 2 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "rebrilhar-verniz",
        "name": "Rebrilhar (5/10/20 L)",
        "brand": "Rebrilhar",
        "image": "img/Rebrilhar_5L.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 12,
        "unit": "M²/L",
        "ncm": "3909.10.00",
        "cest": "28.057.00",
        "barcode": "n/a",
        "model": "5L/10L/20L",
        "category": "Acabamento",
        "coverage": "12 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "12 a 15 Horas (Entre demãos)",
        "cure_time": "30 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "recanto-cola-pu-calafeto",
        "name": "Cola PU Recanto (Calafetacao)",
        "brand": "Recanto",
        "image": "img/Recanto_ColaPU.jpg",
        "weight": 5,
        "measure_unit": "kg",
        "type": "consumption",
        "value": 4,
        "unit": "M²/Kg",
        "ncm": "3506.91.90",
        "cest": "28.063.00",
        "barcode": "n/a",
        "model": "Standard",
        "category": "Acabamento",
        "coverage": "4 M²/Kg",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "n/a",
        "drying_time": "30 a 60 Minutos (Manuseio)",
        "cure_time": "24 Horas",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "recanto-cola-pu-colagem",
        "name": "Cola PU Recanto (Colagem)",
        "brand": "Recanto",
        "image": "img/Recanto_ColaPU.jpg",
        "weight": 5,
        "measure_unit": "kg",
        "type": "consumption",
        "value": 0.3,
        "unit": "M²/Kg",
        "ncm": "3506.91.90",
        "cest": "28.063.00",
        "barcode": "n/a",
        "model": "Standard",
        "category": "Acabamento",
        "coverage": "0.3 M²/Kg",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "n/a",
        "drying_time": "30 a 60 Minutos (Manuseio)",
        "cure_time": "24 Horas",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "recanto-seladora-selamaster",
        "name": "Seladora Selamaster",
        "brand": "Recanto",
        "image": "https://placehold.co/500x500",
        "weight": 3.6,
        "measure_unit": "l",
        "type": "coverage",
        "value": 12,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "Standard",
        "category": "Acabamento",
        "coverage": "12 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "LÍQUIDO DE COPOLÍMEROS PU/ ACRILATOS EMULSIONADOS EM ÁGUA E ADITIVOS COMPONENTES PERIGOSOS COMPONENTEAPROX",
        "odor": "CARACTERÍSTICO",
        "color": "BRANCO LEITOSOp H DILUIDO (1% p/p): N/A",
        "consistency": "LÍQUIDOp H PURO: 7,5 A 8,5",
        "tonality": "n/a",
        "drying_time": "3 a 4 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "recanto-verniz-lumina-fort",
        "name": "Verniz Lumina Fort",
        "brand": "Recanto",
        "image": "https://placehold.co/500x500",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 14,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "Standard",
        "category": "Acabamento",
        "coverage": "14 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "3 a 4 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "sayerlack-maritimo-poliulack",
        "name": "Verniz Marítimo Poliulack",
        "brand": "Sayerlack",
        "image": "img/Sayerlack_Poliulack_Maritimo.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 10,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "900ml/3.6L",
        "category": "Acabamento",
        "coverage": "10 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "4 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "sayerlack-polideck",
        "name": "Verniz Polideck Natural",
        "brand": "Sayerlack",
        "image": "img/Sayerlack_Polideck.webp",
        "weight": 3.6,
        "measure_unit": "l",
        "type": "coverage",
        "value": 8,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "900ml/3.6L",
        "category": "Acabamento",
        "coverage": "8 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Fosco",
        "drying_time": "4 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "sayerlack-polisten-transparente",
        "name": "Verniz Polisten Transparente",
        "brand": "Sayerlack",
        "image": "img/Sayerlack_Polisten.jpg",
        "weight": 3.6,
        "measure_unit": "l",
        "type": "coverage",
        "value": 15,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "900ml/3.6L",
        "category": "Acabamento",
        "coverage": "15 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "4 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "sayerlack-poliulack-brilhante",
        "name": "Verniz Poliulack - Brilhante",
        "brand": "Sayerlack",
        "image": "img/Sayerlack_Poliulack.jpg",
        "weight": 3.6,
        "measure_unit": "l",
        "type": "coverage",
        "value": 10,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "900ml/3.6L",
        "category": "Acabamento",
        "coverage": "10 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "4 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "skania-best-45",
        "name": "Skania Best (45)",
        "brand": "Skania",
        "image": "img/Skania_Best45.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 14,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "14 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "3 Horas (Entre demãos) / 24 Horas (Tráfego leve)",
        "cure_time": "3 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "skania-casa-1k-45",
        "name": "Skania Casa 1k 45",
        "brand": "Skania",
        "image": "img/Skania_Casa1K45.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 14,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "14 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "3 Horas (Entre demãos) / 24 Horas (Tráfego leve)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "skania-super-clean",
        "name": "Skania Limpador Super Clean",
        "brand": "Skania",
        "image": "img/Skania_Limpador.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 50,
        "unit": "M²/L",
        "ncm": "3402.39.90",
        "cest": "11.007.00",
        "barcode": "n/a",
        "model": "1L",
        "category": "Acabamento",
        "coverage": "50 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "n/a",
        "drying_time": "n/a",
        "cure_time": "n/a",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "skania-sealmaster",
        "name": "Skania Sealmaster",
        "brand": "Skania",
        "image": "img/Skania_Sealmaster.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 14,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "14 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "3 Horas (Entre demãos) / 24 Horas (Tráfego leve)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "skania-solid-oil",
        "name": "Skania Solid Oil Transparente",
        "brand": "Skania",
        "image": "img/Skania_Solid.jpg",
        "weight": 5,
        "measure_unit": "l",
        "type": "coverage",
        "value": 20,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "20 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "3 Horas (Entre demãos) / 24 Horas (Tráfego leve)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "varathane-verniz",
        "name": "Varathane Verniz (Uso Geral)",
        "brand": "Varathane",
        "image": "img/Varathane_Floorfinish.jpg",
        "weight": 3.78,
        "measure_unit": "l",
        "type": "manual",
        "value": 12,
        "unit": "M²/L",
        "ncm": "3209.10.20",
        "cest": "24.001.00",
        "barcode": "n/a",
        "model": "Standard",
        "category": "Acabamento",
        "coverage": "12 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "3 a 4 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "ww-cera-resistente",
        "name": "Cera Resistente",
        "brand": "W&W",
        "image": "img/W&W_CeraBrilho.jpg",
        "weight": 1,
        "measure_unit": "l",
        "type": "coverage",
        "value": 70,
        "unit": "M²/L",
        "ncm": "3209.90.19",
        "cest": "10.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "70 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "LÍQUIDO DE COPOLÍMEROS PU/ ACRILATOS EMULSIONADOS EM ÁGUA E ADITIVOS COMPONENTES PERIGOSOS COMPONENTEAPROX",
        "odor": "CARACTERÍSTICO",
        "color": "BRANCO LEITOSOp H DILUIDO (1% p/p): N/A",
        "consistency": "LÍQUIDOp H PURO: 7,5 A 8,5",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "3 a 4 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "ww-cera-laminados",
        "name": "Cera Resistente Laminados/Vinílicos",
        "brand": "W&W",
        "image": "img/W&W_CeraVinilicaBrilho.jpg",
        "weight": 1,
        "measure_unit": "l",
        "type": "coverage",
        "value": 70,
        "unit": "M²/L",
        "ncm": "3209.90.19",
        "cest": "10.001.00",
        "barcode": "n/a",
        "model": "1L/5L",
        "category": "Acabamento",
        "coverage": "70 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "Brilhante/Semi-Brilho/Fosco",
        "drying_time": "3 a 4 Horas (Entre demãos)",
        "cure_time": "7 Dias",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "ww-limpador-conc",
        "name": "Limpador Concentrado",
        "brand": "W&W",
        "image": "img/W&W_Limpador.jpg",
        "weight": 1,
        "measure_unit": "l",
        "type": "coverage",
        "value": 100,
        "unit": "M²/L",
        "ncm": "3402.39.90",
        "cest": "11.007.00",
        "barcode": "n/a",
        "model": "1L",
        "category": "Acabamento",
        "coverage": "100 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "LÍQUIDO NÃO IONICO SOLUVEL EM AGUA",
        "odor": "CARACTERÍSTICO",
        "color": "VERDE CLARO",
        "consistency": "LÍQUIDOp H PURO: 8,0 A 9,0",
        "tonality": "n/a",
        "drying_time": "n/a",
        "cure_time": "n/a",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    },
    {
        "id": "ww-removedor",
        "name": "Removedor Concentrado",
        "brand": "W&W",
        "image": "img/W&W_Removedor.jpg",
        "weight": 1,
        "measure_unit": "l",
        "type": "coverage",
        "value": 150,
        "unit": "M²/L",
        "ncm": "3402.39.90",
        "cest": "11.007.00",
        "barcode": "n/a",
        "model": "1L",
        "category": "Acabamento",
        "coverage": "150 M²/L",
        "roller": "Rolo de Microfibra 10mm",
        "fisqp": "#",
        "bulletin": "#",
        "composition": "Base Água/Solvente",
        "odor": "Baixo",
        "color": "Incolor/Trânsip",
        "consistency": "Líquido Viscoso",
        "tonality": "n/a",
        "drying_time": "n/a",
        "cure_time": "n/a",
        "resistance": "Alto Tráfego",
        "special_resistance": "Risco e Abrasão"
    }
];

// Tornar global para acesso em outros scripts
if (typeof window !== 'undefined') {
    window.productsData = products;
}
