-- 1. Tabela de Mensagens
-- Cria a tabela para armazenar os textos e links das imagens
create table if not exists public.newsletter_messages (
  id bigint generated by default as identity primary key,
  content text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ativa segurança (Row Level Security) mas permite acesso público para simplificar por enquanto
alter table public.newsletter_messages enable row level security;

-- Política de Leitura (Todo mundo pode ler)
create policy "Enable read access for all users"
on public.newsletter_messages for select
using (true);

-- Política de Escrita (Todo mundo pode escrever)
create policy "Enable insert for all users"
on public.newsletter_messages for insert
with check (true);

-- Política de Deleção (Todo mundo pode deletar)
create policy "Enable delete for all users"
on public.newsletter_messages for delete
using (true);


-- 2. Storage (Armazenamento de Imagens)
-- Cria um bucket (pasta) público chamado 'newsletter_images'
insert into storage.buckets (id, name, public)
values ('newsletter_images', 'newsletter_images', true);

-- Permite acesso público para ver as imagens
create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'newsletter_images' );

-- Permite uploads públicos para esse bucket
create policy "Public Upload"
on storage.objects for insert
with check ( bucket_id = 'newsletter_images' );

-- Permite deletar imagens (Opcional, mas útil para limpeza)
create policy "Public Delete"
on storage.objects for delete
using ( bucket_id = 'newsletter_images' );
